baseURL = "https://zishu.me"
theme = 'hugo-bearblog'
title = "子舒的博客"
author = "子舒"
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/blog/:slug.html/"
  

[params]
  description = "子舒的博客，不如吃茶去。"
  mainSections = ['blog']
  buildDate = "2020-06-14"
  author = "子舒"
  twikooID = "https://twikoo.zishu.me/.netlify/functions/twikoo"
  title = "Hugo ʕ•ᴥ•ʔ Bear"
  hideMadeWithLine = true
  dateFormat = "2006-01-02"
