baseurl: https://zishu.me
title: 子舒的博客
languageCode: en-us
paginate: "10"
summaryLength: "1"
theme: mainroad

Author:
  name: 子舒
  bio: "前端程序员, 独立博客作者, 骑行爱好者, 摄影爱好者, INFJ 人格"
  avatar: https://imgurl.zishu.me/author.webp

permalinks:
  blog: /blog/:slug.html/

Params:
  description: John Doe's Personal blog about everything
  opengraph: true
  twitter_cards: false
  readmore: false
  authorbox: true
  pager: true
  post_meta:
    - date
    - categories
  mainSections:
    - blog
    - docs
  logo:
    subtitle: 欢迎来到我的博客
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  widgets:
    recent_num: 5
    tags_counter: false
  socials:
    - name: 首页
      link: /
    # - name: 归档
    #   link: /blog/
    - name: 技术
      link: /categories/技术/
    - name: 随笔
      link: /categories/随笔/
    - name: 周刊
      link: /categories/weekly/
    - name: 留言
      link: /message/
    - name: 关于
      link: /about/
