title = "子舒的博客"
theme = "hugo-theme-flat"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 7
baseURL = ""

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[permalinks]
  blog = "/blog/:slug.html/"
  
[params]
description = "子舒的博客，不如吃茶去。"
mainSections = ['blog']
buildDate = "2020-06-14"
author = "子舒"
twikooID = "https://twikoo.zishu.me/.netlify/functions/twikoo"

[[menus.main]]
name = "归档"
url = "/blog/"
weight = 30

[[menus.main]]
name = "留言"
url = "/message/"
weight = 70

[[menus.main]]
name = "关于我"
url = "/about/"
weight = 80

# 2-level sub menus are supported
[[menus.main]]
name = "分类"
weight = 60
[[menus.main]]
parent = "分类"
name = "技术"
url = "/categories/技术/"
[[menus.main]]
parent = "分类"
name = "随笔"
url = "/categories/随笔/"
[[menus.main]]
parent = "分类"
name = "周刊"
url = "/categories/周刊/"