baseURL = ""
languageCode = "en-us"
title = "子舒的博客"
theme = "meteor"
paginate = 7
hasCJKLanguage = true
summaryLength = 80

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 3 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[outputs]
  home = ["HTML", "RSS", "JSON"]

[permalinks]
  blog = "/blog/:slug.html/"
  
[params]
  title = "zishu.me"
  logo = "https://imgurl.zishu.me/author.webp"
  author = "子舒"
  favicon = "https://imgurl.zishu.me/favicon.ico"
  buildDate = "2020-06-14"
  twikooID = "https://twikoo.zishu.me/.netlify/functions/twikoo"

[[params.socials]]
name = "首页"
link = "/"

[[params.socials]]
name = "归档"
link = "/blog/"

[[params.socials]]
name = "技术"
link = "/categories/技术/"

[[params.socials]]
name = "随笔"
link = "/categories/随笔/"

[[params.socials]]
name = "周刊"
link = "/categories/周刊/"

[[params.socials]]
name = "留言"
link = "/message/"

[[params.socials]]
name = "关于"
link = "/about/"


