baseURL: https://zishu.me/
languageCode: en-us
title: 子舒的博客
theme: typlog
paginate: 30 # 首页文章显示个数
summaryLength: 60 # 首页文章摘要字数
hasCJKLanguage: true

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2 # 从 h2 开始
    endLevel: 3 # 到 h4 结束
    ordered: false # 生成 ul 而不是 ol

outputs:
  home:
    - HTML
    - RSS
    - JSON

permalinks:
  blog: /blog/:slug.html/ # 文章输出 url 格式

params:
  title: 子舒的博客
  logo: https://imgurl.zishu.me/author.webp # 博主头像
  author: zishu # 博主昵称
  favicon: https://imgurl.zishu.me/favicon.ico # 网站 favicon 图标
  buildDate: 2020-06-14 # 建站日期
  twikooID: https://twikoo.zishu.me/.netlify/functions/twikoo # twikoo id
  # 导航
  socials:
    # - name: 归档
    #   link: /blog/
    # - name: 技术
    #   link: /categories/技术/
    # - name: 随笔
    #   link: /categories/随笔/
    - name: 周刊
      link: /categories/weekly/
    - name: 留言
      link: /message/
    - name: 关于
      link: /about/
    # - name: 画廊
    #   link: https://anghunk.notion.site/155935c878aa4210b71c9052b7f726ff?v=762fadfb010a415ea3644a201e3131cb
