baseURL = "https://blog.joway.io/"
languageCode = "en-us"
title = "Joway's Blog"
theme = "yinyang"

[markup]
  [markup.tableOfContents]  # 文章目录
    endLevel = 3
    ordered = false
  [markup.highlight]
    style ="github"    # 高亮风格
    lineNos = false         # 是否显示行号
  [markup.goldmark]         # 是否在md文件中渲染html代码
    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = "Joway"
  homepage = "https://joway.io/"

[permalinks]
  blog = "/blog/:slug.html/"

[params]
mainSections = ["blog"]
headTitle = "子舒"

[[params.socials]]
name = "归档"
link = "/blog/"

[[params.socials]]
name = "留言"
link = "/message/"

[[params.socials]]
name = "关于"
link = "/about/"

[[params.socials]]
name = "实验室"
link = "/lab/"

[[params.socials]]
name = "GPT"
link = "/gpt/"


postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []