baseURL: https://zishu.me/
languageCode: en-us
title: 子舒的博客
theme: paper
paginate: 6 # 首页文章显示个数
summaryLength: 60 # 首页文章摘要字数
hasCJKLanguage: true

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2 # 从h2开始
    endLevel: 3 # 到h4结束
    ordered: false # 生成 ul 而不是 ol
outputs:
  home:
    - HTML
    - RSS
    - JSON
permalinks:
  blog: /blog/:slug.html/ # 文章输出url格式
params:
  title: 子舒的博客
  logo: https://imgurl.zishu.me/author.webp # 博主头像
  author: zishu # 博主昵称
  favicon: https://imgurl.zishu.me/favicon.ico # 网站favicon图标
  buildDate: 2020-06-14 # 建站日期
  twikooID: https://twikoo.zishu.me/.netlify/functions/twikoo # twikoo id
  # 导航
  socials:
    - name: 首页
      link: /
    # - name: 归档
    #   link: /blog/
    - name: 技术
      link: /categories/技术/
    - name: 随笔
      link: /categories/随笔/
    - name: 周刊
      link: /categories/weekly/
    - name: 留言
      link: /message/
    - name: 关于
      link: /about/
