baseURL = ""
languageCode = "en-US"
title = "子舒的博客"
theme = "gists"
pygmentsCodeFences = true
paginate = 10
summaryLength = 100

[permalinks]
  blog = "/blog/:slug.html/"


[params]
  author = "子舒"
  resume = ""
  description = "不如吃茶去"
  email = "anghunk@gmail.com"
  github = "98zi"
  keywords = "blog, minimal, technical"
  rss = true
  title = "zishu.me"
  logo = "https://imgurl.zishu.me/author.png"
  buildDate = "2020-06-14"
  twikooID = "https://twikoo.zishu.me/.netlify/functions/twikoo"